### ISSUE TITLE
Vybrat Backend framework

### ISSUE THREAD

**Issue by OndrejHana** [SuicideSquadJecnaEdition/maturitest#1]

**Comment by OndrejHana** [comment]
Přípustné možnosti obsahují:

- Django
- Asp.net
- Flask
- Laravel
- Symfony

**Comment by OndrejHana** [comment]
Já nechci dělat v PHP, takže se přikláním k jednomu z následujících

- Django
- Asp.net
- Flask

**Comment by Filip-Fer** [comment]
Přikláním se k použití Python web frameworku

- Django
- Flask

**Comment by AnToniceQ** [comment]
V Djangu je lepší dokumentace na HTML templates = PROSÍM DJANGO.

**Comment by OndrejHana** [comment]
@Filip-Fer Pane kapitán prosím o ověření a uzavření Issue
Jako backend framework bylo vybráno Django

**Comment by Filip-Fer** [comment]
Uzavírám. Jako backend web framework bylo vybráno Django

**Comment by Filip-Fer** [comment]
@OndrejHana  @ThonyPig  byl zde návrh od Petra že se změní framework na Laravel a že to všechno napíše, Tondovi pak frontend věci vysvětlí

**Comment by OndrejHana** [comment]
Já klidně budu testovat, alespoň nemusím nic dělat xd

**Comment by Filip-Fer** [comment]
Uzavření výběru backend frameworku. Je vybrán Laravel a jako dev bude nyní @W0lf1n , testerem se stává @OndrejHana .
