### ISSUE TITLE
Hotové wireframes - discussion

### ISSUE THREAD

**Issue by AnToniceQ** [SuicideSquadJecnaEdition/maturitest#17]
Zde zasílám mnou zhotovený wireframe stránek ve Figmě:

https://www.figma.com/file/oqUAFfVhdtHh6s4YxGGetZ/Untitled?node-id=0%3A1

Je vše v pořádku? Máte nějaké námitky? Pochvaly? :P

Jestli se nikdo neozve do WA hodiny požaduji tento wireframe jakožto vhodný k odevzdání.

**Comment by AnToniceQ** [comment]
Dodávám také že mi vytvoření Wireframu trvalo zhruba 2 hodiny čistého času, které obsahovalo i základní naučení Figmy.

**Comment by Filip-Fer** [comment]
Ahoj, wireframe vypadá skvěle uzavírám issue. Hodiny máš zapsané.
