### ISSUE TITLE
Accessibility: Kontrast u jednotlivých otázek 

### ISSUE THREAD

**Issue by OndrejHana** [SuicideSquadJecnaEdition/maturitest#26]
čísla a text jsou odděleny pouze barvou- u toho mohou mít někteří uživatelé problém s jejich rozlišením. 

Návrh: oddělit je navíc nějakým znakem, viz.

```
1) Adresování a správa paměti...
1. Adresování a správa paměti...
```

**Comment by AnToniceQ** [comment]
Hotovo, barva zmizela, wawe s tím již nemá problém a tudíž uzavírám issue.
