### ISSUE TITLE
Vytvořit postup pro time tracking na projektu

### ISSUE THREAD

**Issue by OndrejHana** [SuicideSquadJecnaEdition/maturitest#5]
Podle zadání bude potřeba trackovat čas, strávený na projektu. 
Z vlastních zkušeností doporučuji aplikaci Toggl
https://toggl.com/
Funguje jak na webu, tak i na ios a android

**Comment by Filip-Fer** [comment]
Má někdo ještě návrh na jinou time tracking apku nebo jiný způsob time trackingu?

**Comment by W0lf1n** [comment]
Můžeme použít co navrhuje @OndrejHana

**Comment by Filip-Fer** [comment]
Budete si zapisovat své odpracované hodiny do Excel souboru. Link nasdílím v #22 .
