### ISSUE TITLE
Vybrat hosting

### ISSUE THREAD

**Issue by OndrejHana** [SuicideSquadJecnaEdition/maturitest#6]

**Comment by OndrejHana** [comment]
Já navrhuji Cloud hosting přes 
Railway: https://railway.app/ - Jednoduchý cloud hosting na AWS, mají přímo template pro hostování django serveru
AWS: více manuálního nastavování - Nginx, apod.

**Comment by Filip-Fer** [comment]
Hosting a databáze spadá do @W0lf1n kompetencí, proto bude vše na jeho VPS, omlouvám se mu tím za nepředání informací, na kterých jsme se domluvili.
