### ISSUE TITLE
Jak bude vypadat předmět?

### ISSUE THREAD

**Issue by OndrejHana** [SuicideSquadJecnaEdition/maturitest#7]
Jaká data bude každý předmět obsahovat?

Zatím to vidím na něco jako:
- název
- popis (má být jako plaintext, Markdown nebo HTML?)
- maturitní otázky
- odpovědi k maturitním otázkám

**Comment by AnToniceQ** [comment]
popis může být plaintext.
Může existovat něco jako Article ke každý odpovědi, ve kterém bude nadpis toho úseku a poté text. Ke každému article může být také přidáno 0 či více obrázků.

Tak to vidím nějak já - Těma Articlama mažeme vpodstatě povinnost psát HTML tagy do odpovědi k maturitním otázkám, jelikož ty Articly jako takový budou již mít hezkou strukturu mnou vytvořenou + pod každým Articlem budou přiložené obrázky. Takhle by to mohlo být fajn.

**Comment by AnToniceQ** [comment]
Uzavírám issue, předmět je již designutý.
